
DROP TYPE IF EXISTS car_status CASCADE;
DROP TYPE IF EXISTS booking_status CASCADE;
DROP TYPE IF EXISTS photo_stage CASCADE;
DROP TYPE IF EXISTS photo_angle CASCADE;
DROP TYPE IF EXISTS token_status CASCADE;


CREATE TYPE car_status AS ENUM ('available', 'unavailable', 'booked');
CREATE TYPE booking_status AS ENUM ('active', 'canceled', 'completed');
CREATE TYPE photo_stage AS ENUM ('before', 'after');
CREATE TYPE photo_angle AS ENUM ('front_interior', 'rear_interior', 'front_view', 'rear_view', 'left_side', 'right_side');
CREATE TYPE token_status AS ENUM ('active', 'expired');


DROP TABLE IF EXISTS photos CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS cars CASCADE;
DROP TABLE IF EXISTS tokens CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS bot_message CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "telegram_id" bigint UNIQUE,
  "full_name" varchar,
  "phone_number" varchar,
  "description" text,
  "created_at" timestamp,
  "admin" boolean DEFAULT FALSE
);

CREATE TABLE "cars" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model" varchar,
  "number_plate" varchar,
  "status" car_status DEFAULT 'available',
  "is_enable" boolean DEFAULT TRUE
);

CREATE TABLE "bookings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "car_id" int,
  "start_time" timestamp,
  "end_time" timestamp,
  "status" booking_status DEFAULT 'active'
);

CREATE TABLE "photos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id" int,
  "stage" photo_stage,
  "angle" photo_angle,
  "file_path" varchar,
  "uploaded_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "tokens" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "token" varchar,
  "expires_at" timestamp,
  "status" token_status DEFAULT 'active'
);

CREATE TABLE "bot_message" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "command" varchar,
  "text" text,
  "image_path" varchar
);

CREATE TABLE "reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "telegram_id" bigint,
  "car_id" int,
  "booking_id" int,
  "review" text,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "bookings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "bookings" ADD FOREIGN KEY ("car_id") REFERENCES "cars" ("id");
ALTER TABLE "photos" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id");
ALTER TABLE "tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "reviews" ADD FOREIGN KEY ("telegram_id") REFERENCES "users" ("telegram_id");
ALTER TABLE "reviews" ADD FOREIGN KEY ("car_id") REFERENCES "cars" ("id");
ALTER TABLE "reviews" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id");

INSERT INTO bot_message (command, text, image_path)
VALUES (
  'start',
  '🚗 Добро пожаловать в корпоративный сервис бронирования автомобилей!
Мы помогаем сотрудникам быстро и удобно бронировать служебный транспорт для рабочих поездок.

🔹 Бронирование авто за пару кликов
🔹 Подтверждение доступности онлайн
🔹 История поездок всегда под рукой',
  'welcome.jpg'
);
